send_message:
  description:
    Send message to teacher.
  fields:
    teacher:
      description: Teacher ID.
      example: 1001
    title:
      description: Message title.
      example: "Vulcan for Home Assistant"
    content:
      description: Message content.
      example: "This message has been sent using Vulcan for Home Assistant."
